version: '3'
services:
  speedtester:
    container_name: speedtester
    build: .
    restart: unless-stopped
    image: speedtester
    environment:
      INTERVAL: 600
    logging:
      driver: splunk
      options:
        splunk-url: https://{splunk-url}:8088
        splunk-insecureskipverify: "true"
        splunk-token: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        splunk-source: speedtester.py
        splunk-sourcetype: json
        splunk-format: json
        splunk-index: speedtester
